[project]
name = 'src'
version = '0.0.1'
description = "A Machine Learning project for productionizing models"
authors = [{name = 'Aniket Paswan', email='anikk0208@gmail.com'}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
